theme: jekyll-theme-leap-day
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: BLE-enabled HID based on Edge Inference Accelerated Handwriting Recognition
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
