theme: jekyll-theme-leap-day
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: BLE-enabled Human Interface Devices Based on Edge Inference Accelerated Handwritten Characters Recognition using Low-power Microcontroller
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
